version: '3.8'

services: 
  app:
    build:
      context: ./backend/docker/php
      dockerfile: Dockerfile
    container_name: notes-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql

  frontend: 
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: notes-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev -- --host

  
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: notes-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
  mysql: 
    image: mysql:8.0
    platform: linux/amd64
    container_name: notes-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_PASSWORD: 123456
      MYSQL_USER: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64 
    container_name: notes-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: 123456
    ports:
      - "8888:80"
    depends_on:
      - mysql

volumes:
  mysql_data: